import Vue from "vue";

import Avatar from "@/components/base/Avatar";
import Breadcrumb from "@/components/base/Breadcrumb";
import Button from "@/components/base/Button";
import Card from "@/components/base/Card";
import Expert from "@/components/base/Expert";
import Icon from "@/components/base/Icon";
import Lang from "@/components/base/Lang";
import List from "@/components/base/List";
import Logo from "@/components/base/Logo";
import Notation from "@/components/base/Notation";
import Quote from "@/components/base/Quote";
import Review from "@/components/base/Review";
import SvgSprite from "@/components/base/SvgSprite";
import User from "@/components/base/User";
import Subscribe from "@/components/base/Subscribe";
import Hamburger from "@/components/base/Hamburger";
import Input from "@/components/base/Input";
import Share from "@/components/base/Share";
import Block from "@/components/base/Block";
import Rank from "@/components/base/Rank";
import CircleProgress from "@/components/base/CircleProgress";
import Toggle from "@/components/base/Toggle";
import Textarea from "@/components/base/Textarea";
import Checkbox from "@/components/base/Checkbox";
import Radio from "@/components/base/Radio";

Vue.component("Avatar", Avatar);
Vue.component("Breadcrumb", Breadcrumb);
Vue.component("Button", Button);
Vue.component("Card", Card);
Vue.component("Expert", Expert);
Vue.component("Icon", Icon);
Vue.component("Lang", Lang);
Vue.component("List", List);
Vue.component("Logo", Logo);
Vue.component("Notation", Notation);
Vue.component("Quote", Quote);
Vue.component("Review", Review);
Vue.component("SvgSprite", SvgSprite);
Vue.component("Logo", Logo);
Vue.component("User", User);
Vue.component("Subscribe", Subscribe);
Vue.component("Hamburger", Hamburger);
Vue.component("Input", Input);
Vue.component("Share", Share);
Vue.component("Block", Block);
Vue.component("Rank", Rank);
Vue.component("CircleProgress", CircleProgress);
Vue.component("Toggle", Toggle);
Vue.component("Textarea", Textarea);
Vue.component("Checkbox", Checkbox);
Vue.component("Radio", Radio);
